name = "kissfft-f"
version = "1.0.0"
license = "BSD-3-Clause"
author = "左志华"
maintainer = "zuo.zhihua@qq.com"
copyright = "Copyright 2023, 左志华"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
link = "kissfft"
[install]
library = true
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

